# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).
#
# Examples:
#
#   cities = City.create([{ name: 'Chicago' }, { name: 'Copenhagen' }])
#   Mayor.create(name: 'Emanuel', city: cities.first)
Ubigeo.create(district: 'Lima', department: 'Lima')
Ubigeo.create(district: 'Ancón', department: 'Lima')
Ubigeo.create(district: 'Ate', department: 'Lima')
Ubigeo.create(district: 'Breña', department: 'Lima')
Ubigeo.create(district: 'Carabayllo', department: 'Lima')
Ubigeo.create(district: 'Chaclacayo', department: 'Lima')
Ubigeo.create(district: 'Chorrillos', department: 'Lima')
Ubigeo.create(district: 'Cieneguilla', department: 'Lima')
Ubigeo.create(district: 'Comas', department: 'Lima')
Ubigeo.create(district: 'El Agustino', department: 'Lima')
Ubigeo.create(district: 'Independencia', department: 'Lima')
Ubigeo.create(district: 'Jesús María', department: 'Lima')
Ubigeo.create(district: 'La Molina', department: 'Lima')
Ubigeo.create(district: 'La Victoria', department: 'Lima')
Ubigeo.create(district: 'Lince', department: 'Lima')
Ubigeo.create(district: 'Los Olivos', department: 'Lima')
Ubigeo.create(district: 'Lurin', department: 'Lima')
Ubigeo.create(district: 'Magdalena del Mar', department: 'Lima')
Ubigeo.create(district: 'Pueblo Libre', department: 'Lima')
Ubigeo.create(district: 'Miraflores', department: 'Lima')
Ubigeo.create(district: 'Pachacamac', department: 'Lima')
Ubigeo.create(district: 'Pucusana', department: 'Lima')
Ubigeo.create(district: 'Puente Piedra', department: 'Lima')
Ubigeo.create(district: 'Punta Hermosa', department: 'Lima')
Ubigeo.create(district: 'Punta Negra', department: 'Lima')
Ubigeo.create(district: 'Rímac', department: 'Lima')
Ubigeo.create(district: 'San Bartolo', department: 'Lima')
Ubigeo.create(district: 'San Borja', department: 'Lima')
Ubigeo.create(district: 'San Isidro', department: 'Lima')
Ubigeo.create(district: 'San Juan de Lurigancho', department: 'Lima')
Ubigeo.create(district: 'San Juan de Miraflores', department: 'Lima')
Ubigeo.create(district: 'San Luis', department: 'Lima')
Ubigeo.create(district: 'San Martín de Porres', department: 'Lima')
Ubigeo.create(district: 'San Miguel', department: 'Lima')
Ubigeo.create(district: 'Santa Anita', department: 'Lima')
Ubigeo.create(district: 'Santa María del Mar', department: 'Lima')
Ubigeo.create(district: 'Santa Rosa', department: 'Lima')
Ubigeo.create(district: 'Santiago de Surco', department: 'Lima')
Ubigeo.create(district: 'Surquillo', department: 'Lima')
Ubigeo.create(district: 'Villa El Salvador', department: 'Lima')
Ubigeo.create(district: 'Villa María del Triunfo', department: 'Lima')

SpecialFeature.create(name: 'Camera', description: 'Video cam recorder')
SpecialFeature.create(name: 'Security Agent', description: 'Security personnel')

